# Generated by Django 3.2.25 on 2024-04-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolgnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolgnost', models.CharField(max_length=100, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('familia', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('tel', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Емеил')),
                ('date_to_work', models.DateField(verbose_name='Дата приема на работу')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman.dolgnost', verbose_name='Должность')),
            ],
        ),
    ]
