# Generated by Django 3.2.25 on 2024-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('cost', models.FloatField(default=0.0, verbose_name='Цена')),
            ],
        ),
    ]
